// Generated by plotforge-schema. Do not edit by hand.
export const PLOTFORGE_CONTRACT_VERSION = "0.1.0" as const;
export const PLOTFORGE_CONTRACT_SCHEMA_VERSION = 1 as const;

export type ResourceMap = { [key: string]: number };
export type FlagMap = { [key: string]: boolean };
export type ContractEnvelope<T> = { contract_version: typeof PLOTFORGE_CONTRACT_VERSION; schema_version: typeof PLOTFORGE_CONTRACT_SCHEMA_VERSION; payload: T };

export interface GameProject { id: string; title: string; version: string; description: string; entry_scene: string; run_seed: number; }
export interface ResourceDefinition { key: string; label: string; initial: number; min: number; max: number; }
export interface WorldState { resources: ResourceMap; flags: FlagMap; triggered_events: string[]; }
export interface WorldDelta { resource_changes: ResourceMap; resource_sets: ResourceMap; flags: FlagMap; triggered_events: string[]; }
export interface StoryState { current_scene_key: string; completed_scene_keys: string[]; turn: number; }

export interface StoryCraftBible { target_audience?: string | null; genre_promise: string; central_question: string; target_emotions: string[]; core_foreshadowing: string[]; emotional_contract: string[]; pacing_profile: PacingProfile; hook_strategy: HookStrategy; reversal_strategy?: ReversalStrategy | null; prose_style_guide?: string | null; banned_cliches: string[]; reference_modules: ReferenceModule[]; }
export interface PacingProfile { escalation_interval_scenes: number; target_tension_curve: number[]; breather_scene_frequency?: number | null; }
export interface HookStrategy { primary_hook: string; recurring_hook_patterns: string[]; }
export interface ReversalStrategy { cadence_scenes: number; principle: string; }
export interface ReferenceModule { id: string; title: string; summary: string; }
export interface ReferenceAnalysis { id: string; title: string; source: ReferenceSource; summary: string; structure_notes: ReferenceStructureNote[]; tags: string[]; }
export interface ReferenceSource { source_type: ReferenceSourceType; rights: ReferenceRights; citation: string; user_authorized: boolean; }
export type ReferenceSourceType = "user_import" | "public_domain" | "open_license" | "method_template";
export type ReferenceRights = "user_owned" | "user_authorized" | "public_domain" | "open_license" | "generic_method";
export interface ReferenceStructureNote { label: string; summary: string; }
export interface StoryPromise { id: string; text: string; status: StoryPromiseStatus; introduced_at: string; payoff_hint?: string | null; }
export type StoryPromiseStatus = "active" | "complicated" | "paid_off" | "dropped";
export interface PlotThread { id: string; title: string; promise: string; thread_type: PlotThreadType; status: PlotThreadStatus; introduced_at: string; expected_payoff?: string | null; related_characters: string[]; related_world_flags: string[]; last_update: string; }
export type PlotThreadType = "mystery" | "foreshadow" | "relationship" | "political" | "survival" | "custom";
export type PlotThreadStatus = "open" | "escalating" | "resolved" | "deepened" | "paid_off" | "abandoned";
export interface EmotionalArcPoint { scene_key: string; target_emotion: string; intensity: number; }
export interface StoryCraftState { bible: StoryCraftBible; active_promises: StoryPromise[]; emotional_arc: EmotionalArcPoint[]; plot_threads: PlotThread[]; character_arcs: CharacterArc[]; pacing_score?: number | null; tension_score?: number | null; ai_slop_risk?: number | null; review_notes: NarrativeReviewNote[]; }
export interface CharacterArc { id: string; character_id: string; desire: string; pressure: string; current_state: string; target_state: string; status: CharacterArcStatus; }
export type CharacterArcStatus = "setup" | "pressured" | "changed" | "resolved";
export interface NarrativeReviewNote { id: string; scene_key?: string | null; severity: Severity; message: string; resolved: boolean; }

export interface Character { id: string; name: string; role: string; traits: string[]; visual_card: string; voice_card: string; }
export type AssetKind = "image" | "audio" | "voice" | "data";
export type AssetSourceKind = "user_import" | "generated" | "placeholder" | "external";
export type AssetReferenceKind = "project" | "scene" | "character" | "export_profile";
export interface AssetReference { reference_kind: AssetReferenceKind; reference_id: string; slot: string; }
export interface AssetProviderMetadata { provider: string; model?: string | null; request_id?: string | null; prompt_hash?: string | null; fallback_used: boolean; }
export interface AssetRecord { id: string; kind: AssetKind; source: AssetSourceKind; project_path: string; export_path: string; content_hash: string; hash_algorithm: string; byte_length: number; provider_metadata?: AssetProviderMetadata | null; references: AssetReference[]; }
export interface Scene { key: string; title: string; location: string; dramatic_purpose: string; hook: string; background_asset: string; character_ids: string[]; plot_thread_updates: Record<string, string>; beats: Beat[]; }
export interface Beat { id: string; text: string; choices: Choice[]; }
export interface Choice { id: string; label: string; action_type: string; dramatic_purpose: string; change_scene: boolean; }

export type AgentRole = "story_architect" | "story_craft_planner" | "scene_planner" | "beat_writer" | "plot_doctor" | "consistency_checker" | "deslop_refiner";
export interface AgentOutputProposal { id: string; agent: AgentRole; output: AgentProposalPayload; }
export type AgentProposalPayload = { kind: "scene_plan"; payload: ScenePlanProposal } | { kind: "beat_drafts"; payload: BeatDraftsProposal } | { kind: "review"; payload: ReviewProposal };
export interface ScenePlanProposal { scene_key: string; title: string; location: string; scene_summary: string; dramatic_purpose: string; hook: string; emotional_goal?: string | null; cast: string[]; entry_beat_id: string; background_asset?: string | null; }
export interface BeatDraftsProposal { scene_key: string; beats: BeatDraftProposal[]; }
export interface BeatDraftProposal { id: string; scene_key: string; text: string; choices: Choice[]; narrative_function: NarrativeFunction; }
export type NarrativeFunction = "hook" | "setup" | "payoff" | "reversal" | "choice" | "cliffhanger";
export interface ReviewProposal { scene_key: string; review: NarrativeReview; notes: NarrativeReviewNote[]; }

export interface ActionIntent { status: ActionIntentStatus; action_type?: string | null; matched_terms: string[]; reason?: string | null; }
export type ActionIntentStatus = "supported" | "unsupported";
export interface Rule { id: string; action_type: string; conditions: Condition[]; effects: Effect[]; }
export type Condition = { kind: "resource_at_least"; key: string; value: number } | { kind: "resource_at_most"; key: string; value: number } | { kind: "flag_equals"; key: string; value: boolean };
export type Effect = { kind: "add_resource"; key: string; amount: number } | { kind: "set_resource"; key: string; value: number } | { kind: "set_flag"; key: string; value: boolean } | { kind: "trigger_event"; event: string };
export interface NarrativeReview { scene_key: string; score: number; hook_score: number; pacing_score: number; character_consistency_score: number; payoff_score: number; choice_meaningfulness_score: number; ai_slop_risk: number; issues: NarrativeIssue[]; }
export interface NarrativeIssue { kind: NarrativeIssueKind; severity: Severity; message: string; }
export type NarrativeIssueKind = "weak_hook" | "no_progress" | "fake_choice" | "out_of_character" | "broken_plot_thread" | "thread_forgotten" | "world_state_ignored" | "too_much_exposition" | "ai_slop_style";
export type Severity = "info" | "warning" | "error";

export interface RuntimeError { code: string; message: string; }
export interface RuntimeRuleResult { action_type: string; delta_empty: boolean; state_committed: boolean; error?: RuntimeError | null; }
export interface RuntimePlannerResult { requested_action_type: string; scene_key?: string | null; fallback_used: boolean; error?: RuntimeError | null; }
export interface RuntimeTraceDiagnostic { stage: RuntimeTraceStage; status: RuntimeTraceStageStatus; message: string; }
export type RuntimeTraceStage = "interpret_action" | "select_choice" | "evaluate_rules" | "plan_scene" | "commit_state";
export type RuntimeTraceStageStatus = "completed" | "fallback" | "error";
export interface RuntimeTrace { id: string; timestamp_ms: number; player_input?: string | null; selected_choice?: string | null; action_intent?: ActionIntent | null; rule_result?: RuntimeRuleResult | null; planner_result?: RuntimePlannerResult | null; diagnostics: RuntimeTraceDiagnostic[]; world_state_before: WorldState; world_state_delta: WorldDelta; world_state_after: WorldState; story_state_before: StoryState; story_state_after: StoryState; narrative_review?: NarrativeReview | null; errors: RuntimeError[]; fallback_used: boolean; }

export type JobKind = "text_generation" | "image_generation" | "tts_generation" | "export_package" | "reference_analysis";
export type JobStatus = "queued" | "running" | "succeeded" | "failed" | "canceled" | "timed_out";
export interface JobProgress { completed_units: number; total_units: number; message?: string | null; }
export interface JobCost { estimated_units: number; spent_units: number; }
export interface JobFailure { code: string; message: string; retryable: boolean; }
export interface JobRecord { id: string; kind: JobKind; status: JobStatus; attempt: number; max_attempts: number; created_at_ms: number; updated_at_ms: number; started_at_ms?: number | null; finished_at_ms?: number | null; timeout_ms: number; progress: JobProgress; cost: JobCost; failure?: JobFailure | null; }

export interface ProjectData { game: GameProject; resources: ResourceDefinition[]; world_state: WorldState; story_state: StoryState; story_craft: StoryCraftState; characters: Character[]; rules: Rule[]; scenes: Scene[]; }
export interface ExportManifest { game: GameProject; entry_scene: string; scenes: Scene[]; assets: string[]; generated_by: string; }
export interface ContractRootSchemas { project_data: ProjectData; runtime_trace: RuntimeTrace; job_record: JobRecord; agent_output_proposal: AgentOutputProposal; reference_analysis: ReferenceAnalysis; asset_record: AssetRecord; export_manifest: ExportManifest; }
