// Generated by plotforge-schema. Do not edit by hand.
export const PLOTFORGE_CONTRACT_VERSION = "0.1.0" as const;
export const PLOTFORGE_CONTRACT_SCHEMA_VERSION = 15 as const;

export type ResourceMap = { [key: string]: number };
export type FlagMap = { [key: string]: boolean };
export type ContractEnvelope<T> = { contract_version: typeof PLOTFORGE_CONTRACT_VERSION; schema_version: typeof PLOTFORGE_CONTRACT_SCHEMA_VERSION; payload: T };
export type ProjectTemplateId = "historical_crisis";
export interface ProjectCreationRequest { template: ProjectTemplateId; concept: string; visual_style: string; voice_enabled: boolean; initial_scene_request: string; }
export interface ProjectCreationReport { project_path: string; template: ProjectTemplateId; concept: string; visual_style: string; voice_enabled: boolean; initial_scene_request: string; files_created: string[]; project: ProjectData; }
export interface WorldEditDocument { world_bible_markdown: string; canon_markdown: string; forbidden_facts: string[]; }
export interface StoryCraftEditDocument { story_bible_markdown: string; style_guide_markdown: string; story_craft: StoryCraftState; }
export interface CharacterEditDocument { characters: Character[]; }
export interface StateVariablesEditDocument { resources: ResourceDefinition[]; initial_world_state: WorldState; initial_story_state: StoryState; }
export interface RulesEditDocument { rules: Rule[]; }

export interface GameProject { id: string; title: string; version: string; description: string; entry_scene: string; run_seed: number; }
export interface ResourceDefinition { key: string; label: string; initial: number; min: number; max: number; }
export interface WorldState { resources: ResourceMap; flags: FlagMap; triggered_events: string[]; }
export interface WorldDelta { resource_changes: ResourceMap; resource_sets: ResourceMap; flags: FlagMap; triggered_events: string[]; }
export interface StoryState { current_scene_key: string; current_beat_id?: string | null; completed_scene_keys: string[]; turn: number; }

export interface StoryCraftBible { target_audience?: string | null; genre_promise: string; central_question: string; target_emotions: string[]; core_foreshadowing: string[]; emotional_contract: string[]; pacing_profile: PacingProfile; hook_strategy: HookStrategy; reversal_strategy?: ReversalStrategy | null; prose_style_guide?: string | null; banned_cliches: string[]; reference_modules: ReferenceModule[]; }
export interface PacingProfile { escalation_interval_scenes: number; target_tension_curve: number[]; breather_scene_frequency?: number | null; }
export interface HookStrategy { primary_hook: string; recurring_hook_patterns: string[]; }
export interface ReversalStrategy { cadence_scenes: number; principle: string; }
export interface ReferenceModule { id: string; title: string; summary: string; }
export interface ReferenceAnalysis { id: string; title: string; source: ReferenceSource; summary: string; structure_notes: ReferenceStructureNote[]; tags: string[]; }
export interface ReferenceSource { source_type: ReferenceSourceType; rights: ReferenceRights; citation: string; user_authorized: boolean; }
export type ReferenceSourceType = "user_import" | "public_domain" | "open_license" | "method_template";
export type ReferenceRights = "user_owned" | "user_authorized" | "public_domain" | "open_license" | "generic_method";
export interface ReferenceStructureNote { label: string; summary: string; }
export interface StoryPromise { id: string; text: string; status: StoryPromiseStatus; introduced_at: string; payoff_hint?: string | null; }
export type StoryPromiseStatus = "active" | "complicated" | "paid_off" | "dropped";
export interface PlotThread { id: string; title: string; promise: string; thread_type: PlotThreadType; status: PlotThreadStatus; introduced_at: string; expected_payoff?: string | null; related_characters: string[]; related_world_flags: string[]; last_update: string; }
export type PlotThreadType = "mystery" | "foreshadow" | "relationship" | "political" | "survival" | "custom";
export type PlotThreadStatus = "open" | "escalating" | "resolved" | "deepened" | "paid_off" | "abandoned";
export interface EmotionalArcPoint { scene_key: string; target_emotion: string; intensity: number; }
export interface StoryCraftState { bible: StoryCraftBible; active_promises: StoryPromise[]; emotional_arc: EmotionalArcPoint[]; plot_threads: PlotThread[]; character_arcs: CharacterArc[]; pacing_score?: number | null; tension_score?: number | null; ai_slop_risk?: number | null; review_notes: NarrativeReviewNote[]; }
export interface CharacterArc { id: string; character_id: string; desire: string; pressure: string; current_state: string; target_state: string; status: CharacterArcStatus; }
export type CharacterArcStatus = "setup" | "pressured" | "changed" | "resolved";
export interface NarrativeReviewNote { id: string; scene_key?: string | null; severity: Severity; message: string; resolved: boolean; }

export interface CharacterPortraitRequest { prompt_summary: string; style: string; target_asset_slot: string; prompt_hash: string; provider_config_hash: string; reference_asset_ids: string[]; fallback_allowed: boolean; }
export interface Character { id: string; name: string; role: string; traits: string[]; visual_card: string; voice_card: string; portrait_request?: CharacterPortraitRequest | null; }
export interface CharacterDraft { id: string; name: string; role: string; traits_text: string; visual_card: string; voice_card: string; }
export interface RuleDraft { id: string; action_type: string; resource_key: string; amount: number; }
export type AssetKind = "image" | "audio" | "voice" | "data";
export type AssetSourceKind = "user_import" | "generated" | "placeholder" | "external";
export type AssetReferenceKind = "project" | "scene" | "character" | "export_profile";
export interface AssetReference { reference_kind: AssetReferenceKind; reference_id: string; slot: string; }
export interface AssetProviderMetadata { provider: string; model?: string | null; request_id?: string | null; prompt_hash?: string | null; fallback_used: boolean; }
export interface AssetRecord { id: string; kind: AssetKind; source: AssetSourceKind; project_path: string; export_path: string; content_hash: string; hash_algorithm: string; byte_length: number; provider_metadata?: AssetProviderMetadata | null; references: AssetReference[]; }
export interface MediaAssetReference { asset_id?: string | null; kind: AssetKind; source: AssetSourceKind; project_path: string; export_path: string; slot: string; }
export interface VisualBible { style_cards: VisualStyleCard[]; }
export interface VisualStyleCard { id: string; title: string; summary: string; prompt: string; palette: string[]; tags: string[]; reference_asset_ids: string[]; }
export interface AudioBible { voice_cards: AudioVoiceCard[]; }
export interface AudioVoiceCard { id: string; title: string; summary: string; voice: string; delivery: string; tags: string[]; sample_text?: string | null; reference_asset_ids: string[]; }
export type ExportProfileTarget = "static_web" | "dynamic_web" | "desktop_bundle" | "steam_workshop" | "steam_submission_kit";
export type ExportProfileCapability = "local_http" | "no_network_player" | "static_assets" | "standalone_package" | "runtime_save_restore" | "provider_backed_generation" | "player_byo_key" | "self_host_backend" | "desktop_shell" | "steam_workshop_metadata" | "steam_submission_evidence";
export interface ExportProfile { id: string; target: ExportProfileTarget; intent: string; capabilities: ExportProfileCapability[]; requires_network_at_runtime: boolean; includes_provider_config: boolean; includes_private_traces: boolean; platform_submission_ready: boolean; notes: string[]; }
export type AiUsageContentKind = "text" | "image" | "audio" | "voice" | "data";
export type AiUsageSourceKind = "project_source" | "local_mock_provider" | "external_provider" | "placeholder" | "user_import";
export interface AiUsageDisclosure { content_kind: AiUsageContentKind; source_kind: AiUsageSourceKind; summary: string; asset_paths: string[]; }
export interface AiProviderSummary { provider: string; model?: string | null; generated_asset_count: number; fallback_asset_count: number; prompt_hashes: string[]; }
export interface AiSafetyPolicy { live_generated_content_enabled: boolean; content_kinds: AiUsageContentKind[]; safety_guardrails: string[]; user_reporting_path: string; moderation_policy: string; human_review_required: boolean; moderation_queue_enabled: boolean; policy_source_path?: string | null; evidence_ids: string[]; policy_hash?: string | null; notices: string[]; }
export interface AiUsageManifest { manifest_version: string; project_id: string; project_version: string; export_profile: ExportProfile; generated_by: string; external_model_calls_during_export: boolean; provider_credentials_included: boolean; raw_provider_responses_included: boolean; private_traces_included: boolean; disclosures: AiUsageDisclosure[]; provider_summaries: AiProviderSummary[]; ai_safety_policy: AiSafetyPolicy; notices: string[]; }
export type WorkshopDraftVisibility = "private_draft" | "friends_only_draft" | "unlisted_draft";
export interface WorkshopPackageFile { path: string; content_hash: string; hash_algorithm: string; byte_length: number; }
export interface DesktopRuntimeDraft { manifest_version: string; project_id: string; project_version: string; export_profile: ExportProfile; static_manifest_path: string; ai_usage_manifest_path: string; build_notes_markdown: string; package_files: WorkshopPackageFile[]; runtime_entrypoint: string; requires_network_at_runtime: boolean; provider_credentials_included: boolean; private_traces_included: boolean; raw_provider_responses_included: boolean; notices: string[]; }
export interface WorkshopItemPackage { manifest_version: string; package_id: string; title: string; description: string; visibility: WorkshopDraftVisibility; preview_image: string; content_root: string; tags: string[]; export_profile: ExportProfile; ai_usage_manifest_path: string; content_files: WorkshopPackageFile[]; notices: string[]; }
export interface WorkshopPublishDraft { manifest_version: string; package_id: string; title: string; description: string; visibility: WorkshopDraftVisibility; preview_image: string; content_root: string; tags: string[]; ai_usage_manifest_path: string; package_files: WorkshopPackageFile[]; generated_by: string; upload_enabled: boolean; requires_explicit_steamworks_credentials: boolean; steamworks_api_called: boolean; notices: string[]; }
export interface SteamSubmissionKitRequest { product_name: string; desktop_build_path?: string | null; store_short_description: string; screenshot_paths: string[]; capsule_asset_paths: string[]; content_warnings: string[]; safety_guardrails: string[]; user_reporting_path: string; moderation_policy: string; build_notes: string[]; }
export interface SteamSubmissionKitDraft { manifest_version: string; product_name: string; workshop_package_id: string; generated_by: string; source_workshop_manifest_path: string; store_copy_markdown: string; checklist_markdown: string; ai_disclosure_markdown: string; content_warnings_markdown: string; asset_references_markdown: string; steam_direct_checklist_markdown: string; content_safety_checklist_markdown: string; packaging_notes_markdown: string; official_reference_urls: string[]; notices: string[]; }
export interface Scene { key: string; title: string; location: string; dramatic_purpose: string; hook: string; background_asset: string; audio_refs: MediaAssetReference[]; character_ids: string[]; plot_thread_updates: Record<string, string>; beats: Beat[]; entry_beat_id?: string | null; }
export interface Beat { id: string; text: string; speaker?: string | null; line_delivery?: string | null; audio_refs: MediaAssetReference[]; choices: Choice[]; next?: BeatNext; }
export type BeatNext = { kind: "beat"; payload: string } | { kind: "scene" } | { kind: "end" } | { kind: "none" };
export interface Choice { id: string; label: string; action_type: string; input_terms: string[]; dramatic_purpose: string; change_scene: boolean; }

export type AgentRole = "story_architect" | "story_craft_planner" | "character_designer" | "scene_planner" | "beat_writer" | "plot_doctor" | "consistency_checker" | "deslop_refiner";
export interface AgentOutputProposal { id: string; agent: AgentRole; output: AgentProposalPayload; }
export interface ReproducibilityMetadata { run_seed: number; prompt_version: string; model_version: string; provider_config_hash: string; trace_id?: string | null; snapshot_id?: string | null; }
export interface AgentOutputEnvelope { id: string; contract_version: string; schema_version: number; agent: AgentRole; reproducibility: ReproducibilityMetadata; proposal: AgentOutputProposal; }
export type AgentProposalPayload = { kind: "world_expansion"; payload: WorldExpansionProposal } | { kind: "story_craft_plan"; payload: StoryCraftPlanProposal } | { kind: "character_profile"; payload: CharacterProposal } | { kind: "scene_plan"; payload: ScenePlanProposal } | { kind: "beat_drafts"; payload: BeatDraftsProposal } | { kind: "review"; payload: ReviewProposal };
export interface WorldGenerationRequest { expansion_goal: string; document: WorldEditDocument; }
export interface WorldExpansionProposal { world_bible_markdown: string; canon_markdown: string; forbidden_facts: string[]; }
export interface WorldGenerationReport { document: WorldEditDocument; evidence: GenerationEvidence; }
export interface StoryCraftGenerationRequest { concept: string; world_bible_markdown: string; canon_markdown: string; forbidden_facts: string[]; document: StoryCraftEditDocument; characters: Character[]; }
export interface StoryCraftPlanProposal { story_bible_markdown: string; style_guide_markdown: string; story_craft: StoryCraftState; }
export interface StoryCraftGenerationReport { document: StoryCraftEditDocument; evidence: GenerationEvidence; }
export interface CharacterGenerationRequest { concept: string; role_hint: string; world_bible_markdown: string; story_bible_markdown: string; existing_characters: Character[]; }
export interface CharacterProposal { character: Character; }
export interface CharacterGenerationReport { character: Character; evidence: GenerationEvidence; }
export interface GenerationEvidence { status: GenerationStatus; fallback_used: boolean; error?: RuntimeError | null; reproducibility: ReproducibilityMetadata; envelopes: AgentOutputEnvelope[]; }
export type GenerationStatus = "succeeded" | "fallback" | "failed";
export interface ScenePlanProposal { scene_key: string; title: string; location: string; scene_summary: string; dramatic_purpose: string; hook: string; emotional_goal?: string | null; cast: string[]; entry_beat_id: string; background_asset?: string | null; }
export interface BeatDraftsProposal { scene_key: string; beats: BeatDraftProposal[]; }
export interface BeatDraftProposal { id: string; scene_key: string; text: string; choices: Choice[]; narrative_function: NarrativeFunction; }
export type NarrativeFunction = "hook" | "setup" | "payoff" | "reversal" | "choice" | "cliffhanger";
export interface ReviewProposal { scene_key: string; review: NarrativeReview; notes: NarrativeReviewNote[]; }

export interface ActionIntent { status: ActionIntentStatus; choice_id?: string | null; action_type?: string | null; matched_terms: string[]; reason?: string | null; }
export type ActionIntentStatus = "supported" | "unsupported";
export interface Rule { id: string; action_type: string; conditions: Condition[]; effects: Effect[]; }
export type Condition = { kind: "resource_at_least"; key: string; value: number } | { kind: "resource_at_most"; key: string; value: number } | { kind: "flag_equals"; key: string; value: boolean };
export type Effect = { kind: "add_resource"; key: string; amount: number } | { kind: "set_resource"; key: string; value: number } | { kind: "set_flag"; key: string; value: boolean } | { kind: "trigger_event"; event: string };
export interface NarrativeReview { scene_key: string; score: number; hook_score: number; pacing_score: number; character_consistency_score: number; payoff_score: number; choice_meaningfulness_score: number; ai_slop_risk: number; issues: NarrativeIssue[]; }
export interface NarrativeIssue { kind: NarrativeIssueKind; severity: Severity; message: string; }
export type NarrativeIssueKind = "weak_hook" | "no_progress" | "fake_choice" | "out_of_character" | "broken_plot_thread" | "thread_forgotten" | "world_state_ignored" | "too_much_exposition" | "ai_slop_style";
export type Severity = "info" | "warning" | "error";

export interface RuntimeError { code: string; message: string; }
export interface RuntimeRuleResult { action_type: string; delta_empty: boolean; state_committed: boolean; error?: RuntimeError | null; }
export interface RuntimePlannerResult { requested_action_type: string; scene_key?: string | null; fallback_used: boolean; error?: RuntimeError | null; }
export interface RuntimeMediaReference { reference: AssetReference; project_path: string; }
export interface RuntimeTraceDiagnostic { stage: RuntimeTraceStage; status: RuntimeTraceStageStatus; message: string; }
export type RuntimeTraceStage = "interpret_action" | "select_choice" | "evaluate_rules" | "plan_scene" | "commit_state";
export type RuntimeTraceStageStatus = "completed" | "fallback" | "error";
export interface RuntimeTrace { id: string; timestamp_ms: number; reproducibility: ReproducibilityMetadata; player_input?: string | null; selected_choice?: string | null; action_intent?: ActionIntent | null; rule_result?: RuntimeRuleResult | null; planner_result?: RuntimePlannerResult | null; diagnostics: RuntimeTraceDiagnostic[]; world_state_before: WorldState; world_state_delta: WorldDelta; world_state_after: WorldState; story_state_before: StoryState; story_state_after: StoryState; narrative_review?: NarrativeReview | null; media_references: RuntimeMediaReference[]; errors: RuntimeError[]; fallback_used: boolean; }
export interface RuntimeSnapshot { id: string; timestamp_ms: number; reproducibility: ReproducibilityMetadata; project_id: string; project_version: string; story_state: StoryState; world_state: WorldState; scenes: Scene[]; }

export type JobKind = "text_generation" | "image_generation" | "tts_generation" | "export_package" | "reference_analysis";
export type JobStatus = "queued" | "running" | "succeeded" | "failed" | "canceled" | "timed_out";
export interface JobProgress { completed_units: number; total_units: number; message?: string | null; }
export interface JobCost { estimated_units: number; spent_units: number; }
export interface JobFailure { code: string; message: string; retryable: boolean; }
export interface JobRecord { id: string; kind: JobKind; status: JobStatus; attempt: number; max_attempts: number; created_at_ms: number; updated_at_ms: number; started_at_ms?: number | null; finished_at_ms?: number | null; timeout_ms: number; progress: JobProgress; cost: JobCost; failure?: JobFailure | null; }

export interface ProjectData { game: GameProject; resources: ResourceDefinition[]; world_state: WorldState; story_state: StoryState; story_craft: StoryCraftState; characters: Character[]; rules: Rule[]; scenes: Scene[]; visual_bible: VisualBible; audio_bible: AudioBible; asset_records: AssetRecord[]; ai_safety_policy: AiSafetyPolicy; }
export interface ExportManifest { game: GameProject; entry_scene: string; scenes: Scene[]; assets: string[]; asset_records: AssetRecord[]; profile: ExportProfile; ai_usage_manifest_path: string; generated_by: string; }
export interface ContractRootSchemas { project_creation_request: ProjectCreationRequest; project_creation_report: ProjectCreationReport; world_edit_document: WorldEditDocument; story_craft_edit_document: StoryCraftEditDocument; character_edit_document: CharacterEditDocument; state_variables_edit_document: StateVariablesEditDocument; rules_edit_document: RulesEditDocument; project_data: ProjectData; runtime_trace: RuntimeTrace; runtime_snapshot: RuntimeSnapshot; job_record: JobRecord; agent_output_proposal: AgentOutputProposal; agent_output_envelope: AgentOutputEnvelope; reproducibility_metadata: ReproducibilityMetadata; generation_evidence: GenerationEvidence; world_generation_request: WorldGenerationRequest; world_generation_report: WorldGenerationReport; story_craft_generation_request: StoryCraftGenerationRequest; story_craft_generation_report: StoryCraftGenerationReport; character_generation_request: CharacterGenerationRequest; character_generation_report: CharacterGenerationReport; character_portrait_request: CharacterPortraitRequest; character_draft: CharacterDraft; rule_draft: RuleDraft; reference_analysis: ReferenceAnalysis; asset_record: AssetRecord; media_asset_reference: MediaAssetReference; visual_bible: VisualBible; audio_bible: AudioBible; ai_safety_policy: AiSafetyPolicy; ai_usage_manifest: AiUsageManifest; desktop_runtime_draft: DesktopRuntimeDraft; workshop_item_package: WorkshopItemPackage; workshop_publish_draft: WorkshopPublishDraft; steam_submission_kit_request: SteamSubmissionKitRequest; steam_submission_kit_draft: SteamSubmissionKitDraft; export_manifest: ExportManifest; }
